services:
  main-db:
    image: ${DB_IMAGE}
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - main-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
